feat: Add callback functionality for capture events
quantity-digital/commerce-quickpay pull request #19
Opened 2024-01-05 12:58 UTC by bjerringgaard

2024-01-08 08:47 UTC, NicolajKN requested changes

2024-01-08 08:47 UTC, NicolajKN commented on src/controllers/PaymentsCallbackController.php
> +		//TODO: Update to use same logic as notify
Should this be addressed?

2024-01-08 08:47 UTC, NicolajKN commented on src/controllers/PaymentsCallbackController.php
> +		//TODO: Update to use same logic as notify
Same?

2024-01-08 08:47 UTC, NicolajKN commented on src/Plugin.php
>  					'quickpay/callbacks/payments/notify/<transactionReference>' => 'commerce-quickpay/payments-callback/notify',
Deprecate

2024-01-08 08:47 UTC, NicolajKN commented on src/services/Orders.php
> +	public function updateOrderStatus(Order $order, BaseGatewayInterface $gateway): void
Should be more descriptive, eg. setAfterCaptureStatus

2024-01-08 08:47 UTC, NicolajKN commented on src/services/PaymentsCallbackService.php
> +    // Get the last transaction state
Comment

2024-01-08 08:47 UTC, NicolajKN commented on src/services/TransactionService.php
> +   * @param TransactionModel $parent
Mismatched with function

2024-01-08 08:47 UTC, NicolajKN commented on src/services/TransactionService.php
> +   * @param TransactionModel $parent
Mismatched

2024-01-08 08:47 UTC, NicolajKN commented on src/services/TransactionService.php
> +  public function createAuthorize(mixed $data, string $status, string $message = ''): TransactionModel
Mixed should be response model (also other methods in this class) + $parentId as first param

2024-01-09 10:00 UTC, bjerringgaard commented on src/controllers/PaymentsCallbackController.php
> +		//TODO: Update to use same logic as notify
Will be addressed in a later version, as to not change to much critical logic

2024-01-09 10:00 UTC, bjerringgaard commented on src/controllers/PaymentsCallbackController.php
> +		//TODO: Update to use same logic as notify
Will be addressed in a later version, as to not change to much critical logic

2024-01-10 13:44 UTC, NicolajKN approved these changes
Looks good, let's test it 🎉

2024-01-22 08:37 UTC, merged